### ISSUE TITLE
Can't select different file types

### ISSUE THREAD

**Issue by nidhinkumar06** [EnriqueGL/cordova-custom-filechooser#1]
I have tried to select .pdf and .png format files but when i give the below code i can't able to select the both.
But if we give one type it works

`customFileChooser.open('application/pdf, image/png', function (uri) {
        $log.log('success uri is', uri);
      }, function (error) {
        $log.log('error is', error);
      });`

**Comment by EnriqueGL** [comment]
**the bug was fixed**. now you can open multiple types of files
